import { ChatContact, ChatThread, Course, CourseUnit, NotificationRow } from './models';

export const COURSES: Course[] = [
  {
    id: 'progra-4',
    code: 'Progra IV',
    title: 'Programación IV',
    cohort: '2da Cohorte 2026',
    progress: 65,
    lives: 5,
    coins: 450,
    tone: 'cyan',
    courseTone: 'celeste',
    status: 'Cursando',
    difficulty: 'advanced',
    language: 'Español',
    durationLabel: '90H',
  },
  {
    id: 'bdd',
    code: 'BDD',
    title: 'Bases de Datos',
    cohort: '1ra Cohorte 2026',
    progress: 40,
    lives: 4,
    coins: 280,
    tone: 'magenta',
    courseTone: 'rosa',
    status: 'Cursando',
    difficulty: 'intermediate',
    language: 'Español',
    durationLabel: '60H',
  },
  {
    id: 'progra-3',
    code: 'Progra III',
    title: 'Programación III',
    cohort: '2da Cohorte 2026',
    progress: 88,
    lives: 5,
    coins: 510,
    tone: 'cyan',
    courseTone: 'celeste',
    status: 'Cursando',
    difficulty: 'intermediate',
    language: 'Español',
    durationLabel: '80H',
  },
  {
    id: 'ingles',
    code: 'Inglés II',
    title: 'Inglés Técnico II',
    cohort: '1ra Cohorte 2026',
    progress: 52,
    lives: 3,
    coins: 190,
    tone: 'magenta',
    courseTone: 'rosa',
    status: 'Cursando',
    difficulty: 'beginner',
    language: 'Inglés',
    durationLabel: '45H',
  },
];

export const COURSE_UNITS: CourseUnit[] = [
  {
    id: 'u1',
    label: 'U1',
    title: 'Arquitectura y Despliegue',
    description: 'Fundamentos de arquitecturas frontend y backend, microfrontends, pipelines y estándares.',
    progress: 100,
    resources: [
      {
        id: 't1',
        section: 'teorico',
        title: 'TUP_PIV_FE_TEO_U1_ARQUITECTURA_DESPLIEGUE.pdf',
        subtitle: 'Microfrontends, Webpack Module Federation y despliegues modernos.',
        size: '2.4 MB',
        tags: ['correccion', 'obligatorio'],
        done: true,
      },
      {
        id: 't2',
        section: 'teorico',
        title: 'TUP_PIV_FE_PROPUESTA_ARQ.pdf',
        subtitle: 'Arquitectura hexagonal en C# y Clean Architecture.',
        size: '1.8 MB',
        tags: ['correccion', 'obligatorio'],
        done: true,
      },
      {
        id: 'v1',
        section: 'audiovisual',
        title: 'SPA en Vercel y Docker',
        subtitle: 'Walkthrough del pipeline de despliegue de la cohorte.',
        size: '42 min',
        tags: ['obligatorio'],
        done: true,
      },
      {
        id: 'a1',
        section: 'apoyo',
        title: 'Checklist de arquitectura',
        subtitle: 'Preguntas para defender el TP 1 ante el docente.',
        size: '1 pág',
        tags: ['opcional'],
        done: true,
      },
      {
        id: 'd1',
        section: 'desafio',
        title: 'Desafío 1: Dockerizar el front',
        subtitle: 'Imagen local + compose con hot reload.',
        size: '+200 XP',
        tags: ['obligatorio'],
        done: true,
      },
    ],
  },
  {
    id: 'u2',
    label: 'U2',
    title: 'Component-Driven Development',
    description: 'Librería de componentes, tokens arcade y composición de pantallas.',
    progress: 60,
    resources: [
      {
        id: 't3',
        section: 'teorico',
        title: 'TUP_PIV_FE_TEO_U2_CDD.pdf',
        subtitle: 'Design system, primitivas y contrato de la librería.',
        size: '3.1 MB',
        tags: ['obligatorio'],
        done: true,
      },
      {
        id: 'v2',
        section: 'audiovisual',
        title: 'Tokens y theming en vivo',
        subtitle: 'Cómo cablear data-theme sin romper el contraste.',
        size: '28 min',
        tags: ['opcional'],
        done: false,
      },
      {
        id: 'd2',
        section: 'desafio',
        title: 'Desafío 2: Card reutilizable',
        subtitle: 'Una card que reciba tone, progreso y acciones.',
        size: '+250 XP',
        tags: ['obligatorio'],
        done: false,
      },
    ],
  },
  {
    id: 'u3',
    label: 'U3',
    title: 'Estado Global y Gestión',
    description: 'Sesión, guards y estado reactivo en el shell de la SPA.',
    progress: 15,
    resources: [
      {
        id: 't4',
        section: 'teorico',
        title: 'TUP_PIV_FE_TEO_U3_ESTADO.pdf',
        subtitle: 'Signals, sesión y límites del estado global.',
        size: '2.0 MB',
        tags: ['obligatorio'],
        done: false,
      },
      {
        id: 'd3',
        section: 'desafio',
        title: 'Desafío 3: AuthGuard',
        subtitle: 'Guard funcional que redirige a login sin zona.',
        size: '+300 XP',
        tags: ['obligatorio'],
        done: false,
      },
    ],
  },
];

export const NOTIFICATIONS: NotificationRow[] = [
  {
    id: 'n1',
    title: '¡NUEVO LOGRO DESBLOQUEADO!',
    description: 'Completaste la Unidad 1 de Programación IV con 100% de efectividad.',
    type: 'logro',
    when: 'Hace 10 min',
    read: false,
    xp: 250,
    coins: 50,
  },
  {
    id: 'n2',
    title: 'NUEVO DESAFÍO EN COHORTE',
    description: 'El docente habilitó el Boss Fight: "Microfrontends con Module Federation". Quedan 3 días.',
    type: 'desafio',
    when: 'Hace 2 horas',
    read: false,
    xp: 500,
  },
  {
    id: 'n3',
    title: 'NUEVO MENSAJE DE COHORTE',
    description: 'Prof. Carlos Rossi respondió en #dudas-tp: "Revisen el diagrama de componentes en el apunte."',
    type: 'mensaje',
    when: 'Hace 4 horas',
    read: true,
  },
  {
    id: 'n4',
    title: 'RECUPERACIÓN DE VIDAS',
    description: 'Tu racha de 5 días activos te otorgó +1 Vida de reserva.',
    type: 'sistema',
    when: 'Ayer',
    read: true,
    coins: 10,
  },
  {
    id: 'n5',
    title: 'TOP 10 ALCANZADO',
    description: 'Subiste al puesto #8 en el Ranking global de la cohorte.',
    type: 'logro',
    when: 'Hace 2 días',
    read: true,
    xp: 100,
  },
];

export const CONTACTS: ChatContact[] = [
  {
    id: 'c1',
    name: 'Comisión A - General',
    role: 'Canal de cohorte (34 alumnos)',
    initials: 'CA',
    lastMessage: 'Prof. Carlos: Mañana cerramos la entrega del TP 1.',
    unread: 2,
  },
  {
    id: 'c2',
    name: 'Prof. Carlos Rossi',
    role: 'Docente titular',
    initials: 'PC',
    lastMessage: 'Perfecto Tamara, revisá la corrección que te envié.',
    unread: 0,
  },
  {
    id: 'c3',
    name: 'Equipo TP - Retro Devs',
    role: 'Grupo TP (4 miembros)',
    initials: 'ET',
    lastMessage: 'Lucas: Ya subí la rama con los componentes.',
    unread: 1,
  },
  {
    id: 'c4',
    name: 'Matias Gomez',
    role: 'Compañero de comisión',
    initials: 'MG',
    lastMessage: '¿A qué hora nos conectamos para probar el boss fight?',
    unread: 0,
  },
];

export const THREADS: ChatThread[] = [
  {
    id: 'c1',
    name: 'Comisión A - General',
    messages: [
      { id: 'm1', text: '¿Alguien pudo armar el despliegue con Docker?', from: 'them' },
      { id: 'm2', text: 'Sí, está el docker-compose de ejemplo en la Unidad 1.', from: 'me' },
      { id: 'm3', text: 'Mañana a las 23:59 cierra el TP 1.', from: 'them' },
    ],
  },
  {
    id: 'c2',
    name: 'Prof. Carlos Rossi',
    messages: [
      { id: 'm4', text: 'Hola Profe, dejé la duda de arquitectura hexagonal.', from: 'me' },
      { id: 'm5', text: 'Perfecto, revisá la corrección que te envié.', from: 'them' },
    ],
  },
  {
    id: 'c3',
    name: 'Equipo TP - Retro Devs',
    messages: [{ id: 'm6', text: 'Ya subí la rama con los componentes.', from: 'them' }],
  },
  {
    id: 'c4',
    name: 'Matias Gomez',
    messages: [{ id: 'm7', text: '¿A qué hora probamos el boss fight?', from: 'them' }],
  },
];
